---
title: "STAT 545 Directory"
author: 'By: Jennica Nichols'
date: "October 20, 2017"
output: 
  html_document:
    toc: true
    keep_md: true
---

# Project Directory Support
This document serves as a guide for the entire project to help when I review this repo in the future to apply what was learned in STAT 545 to my research.

## Assignment 1
[This is the link](/hw01_gapminder_files) for the **first** homework assignment. 

* Edit README.md to include information about myself
* Initial exploration of gapminder


## Assignment 2
[This is the link](/hw02_piping_ggplot) for the **second** homework assignment. 

* Data exploration
    * Categorical and continuous variable exploration
    * Data frame exploration (str() and summary())
    * Inital plots using ggplot()
    
## Assignment 3
[This is the link](/hw03_dplyr_ggplot) for the **third** homework assignment. 

* dplyr exploration
    * summarise()
    * mutate()
    * filter()
    * group_by
    
* graphing using ggplot2
    * geom_point()
    * geom_smooth()
    * geom_line()
    
## Assignment 4
[This is the link](/hw04_tidyr_join) for the **fourth** homework assignment. 

* tidying data using the tidyr package
    * spread()
    * gather()

* practicing joining two datasets in various ways
    * left_join(), right_join(), inner_join()
    * intersect(), union(), setdiff()
    * semi_join(), anti_join()
    
## Assignment 5
[This is the link](/hw05) for the **fifth** homework assignment. 

* creating better graphs using ggplot2
    * look at lecture files on computer for a great lecture about data visualization from a guest lecturer

* more using dplyr
    * arrange()
    
* working with factors using the forcats package
    * fct_reorder()
    * drop_levels()

* writing and reading dataframes using readr package
    * write_csv()
    * read_csv()

* create and embedding image files
    * ggsave()
    